typography_spectrum: 0.942364260321483
color:
  brandStrength: 0.8634829705115408
  lightness: 0.7967067745048553
  saturation: 0.5924122594296932
  rhythmicContrast: 0.3214749551843852
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
layout_spectrum: 0.9145933412946761
name: Valkania
navigation:
  - name: Contact us
    url: band@valkania.com
    type: external
title: Balkan Rhythm'n'Blues Band from London
description: ''
