typography_spectrum: 0.942364260321483
color:
  brandStrength: 0.8634829705115408
  lightness: 0.7967067745048553
  saturation: 0.5924122594296932
  rhythmicContrast: 0.3214749551843852
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
layout_spectrum: 0.9145933412946761
name: Valkania
navigation:
  - name: Newsletter
    url: >-
      http://valkania.us11.list-manage1.com/subscribe?u=26ef188d16edc173173789dd8&id=c639747858
    type: external
  - name: contact us
    url: 'mailto:band@valkania.com'
    type: external
  - name: About Us
    id: 4b7d185b-06a0-4f92-8263-c1154d6bd232
    type: content
title: Valkania
description: Balkan Rhythm'n'Blues Band from London
